include theos/makefiles/common.mk

TWEAK_NAME = GesturizerUIKit
GesturizerUIKit_CFLAGS = -I../Tweak
GesturizerUIKit_LDFLAGS = -L/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.0.sdk/usr/lib/gcc/arm-apple-darwin10/4.2.1/
GesturizerUIKit_FILES = Tweak.xm
GesturizerUIKit_FRAMEWORKS = UIKit
GesturizerUIKit_PRIVATE_FRAMEWORKS = AppSupport GraphicsServices

include $(THEOS_MAKE_PATH)/tweak.mk
